POSTGRES_DB_USER: postgres
POSTGRES_DB_PASSWORD: 123456
POSTGRES_DB_HOST: localhost
POSTGRES_DB_PORT: 5432
POSTGRES_DB_NAME: playpulse
FASTAPI_PORT: 8001
FASTAPI_HOST: 0.0.0.0
FASTAPI_RELOAD: False
LOG_FILE: /var/log/playpulse/app.log